name: Release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

jobs:
  validate-and-test:
    uses: "./.github/workflows/validate-test.yaml"
  release-binary-and-image:
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for ghcr access
    needs: [validate-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Checkout - force fetch tags
        run: git fetch --force --tags
      - name: Tagged build - generate tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "CURRENT_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
      - name: Snapshot build - generate tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          sudo apt-get install -y --no-install-recommends python3-semver
          export NEXT_TAG=$(pysemver nextver $(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0") patch)
          echo "CURRENT_TAG=${NEXT_TAG}-$(git describe --tags | awk -F '-' '{print "dev."$2"."$3}')" >> $GITHUB_ENV
      - name: Generate tag - print the tag
        run: |
          echo "CURRENT_TAG=$CURRENT_TAG"
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.22.2
          cache: true
      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: "amd64,arm64"
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
        with:
          platforms: "linux/amd64,linux/arm64"
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
      - name: Setup Cosign
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
      - name: Setup Helm
        run: |
          curl -L -sS -o helm-v3.16.1-linux-amd64.tar.gz https://get.helm.sh/helm-v3.16.1-linux-amd64.tar.gz
          tar xzf helm-v3.16.1-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          rm -rf helm-v3.16.1-linux-amd64.tar.gz linux-amd64
          helm version
      - name: Setup app-build-suite
        run: curl -fsSL https://github.com/giantswarm/app-build-suite/releases/latest/download/dabs.sh -o /tmp/dabs.sh && chmod +x /tmp/dabs.sh && sed -i 's/docker run -it --rm/docker run --rm/' /tmp/dabs.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: build_bot
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login helm to OCI registry
        run: helm registry login ghcr.io -u build_bot -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Run GoReleaser for tag build
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: "~> v2.3"
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Snapshot build - run GoReleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: "~> v2.3"
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Snapshot build - upload docker images - prepare image list
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: jq -r '.[] | select(.type=="Docker Image" and (.name | contains(":latest") | not)) | .name' dist/artifacts.json | paste -sd ' ' /dev/stdin > images
      - name: Snapshot build - upload docker images - upload images
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: cat images | xargs -d ' ' -I{} -n1 sh -c "docker push {}"
      - name: Snapshot build - upload docker images - create manifests
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker manifest create ghcr.io/giantswarm/demo-album-catalog:$CURRENT_TAG $(cat images)
          docker manifest push ghcr.io/giantswarm/demo-album-catalog:$CURRENT_TAG
      - name: Snapshot build - set helm chart versions
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          yq -i "(.version = env(CURRENT_TAG)) | (.appVersion = env(CURRENT_TAG))" helm/Chart.yaml
          yq -i "(.replace-chart-version-with-git = false) | (.replace-app-version-with-git = false)" .abs/main.yaml
      - name: Run app-build-suite to build the helm chart
        run: |
          yq -i ".image.tag = env(CURRENT_TAG)" helm/values.yaml
          set -o pipefail && /tmp/dabs.sh -c helm 2>&1 | tee /tmp/abs.log
      - name: Capture the helm chart name
        run: >-
          echo "CHART_FILE=$(
            awk -F":" '/packaged chart and saved it to/ {gsub(/ /, ""); print $2}' /tmp/abs.log
          )" >> "$GITHUB_ENV"
      - name: Capture the helm chart version
        run: >-
          echo "CHART_VERSION=$(
            awk -F"[:,]" '/=> \(version/ {gsub(/[ "]/, ""); print $2; exit }' /tmp/abs.log
          )" >> "$GITHUB_ENV"
      - name: Check detected version
        run: '[ -z "${CHART_FILE}" ] && exit 1 || echo "CHART_FILE=${CHART_FILE}"; [ -z "${CHART_VERSION}" ] && exit 1 || echo "CHART_VERSION=${CHART_VERSION}"'
      - name: Push the helm chart to registry
        run: set -o pipefail && helm push "${CHART_FILE}" "oci://ghcr.io/giantswarm/charts" 2>&1 | tee /tmp/helm-push.log
      - name: Capture the helm chart SHA256
        run: >-
          echo "CHART_SHA256=$(
            awk -F" " '/^Digest:/ {print $2}' /tmp/helm-push.log
          )" >> "$GITHUB_ENV"
      - name: Sign the helm chart
        run: cosign sign --upload=true -y "ghcr.io/giantswarm/charts/demo-album-catalog@${CHART_SHA256}"
