name: Template and release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

jobs:
  rendered-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install boilerplate
        run: curl -fsSL https://github.com/gruntwork-io/boilerplate/releases/latest/download/boilerplate_linux_amd64 -o /usr/local/bin/boilerplate && chmod +x /usr/local/bin/boilerplate
      - name: Copy the current state for use with templating
        run: cp -a project-template/ boilerplate-values.yml /tmp
      - name: Checkout rendered project branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: "rendered-project-pack"
      - name: Run boilerplate
        run: boilerplate --non-interactive --template-url /tmp/project-template --output-folder . --var-file /tmp/boilerplate-values.yml
      - name: Install helm-docs
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4 # v1.12.0
        with:
          repo: norwoodj/helm-docs
          tag: v1.11.0
          cache: enable
      - name: Replace source repo info
        run: sed -i 's/org\.opencontainers\.image\.source=https:\/\/github\.com\/giantswarm\/demo-album-catalogpack/org\.opencontainers\.image\.source=https:\/\/github\.com\/giantswarm\/devplatform-template-go-service/' project.toml
      - name: Run pre-commit
        continue-on-error: true
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Commit rendered project
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "rendered-project-pack-${{ github.head_ref }}"
          delete-branch: true
          token: ${{ secrets.WORKFLOW_PAT }}
      - name: Create comment when no change
        if: ${{ !steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Your current PR doesn't make any change in the rendered project. No PR was created.
      - name: Create comment when change
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            A Pull Request was created to preview the result of this PR.
            Make sure you review and accept the created PR before you merge this one!
            Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}
